"""
annual_ssm_dit
==============

Annual-SSM-conditioned outpainting diffusion transformer for regional tas/pr.

Relation to `ssm_dit`
---------------------
`ssm_dit` carried two latent processes behind one interface: the monthly
`DeepSSMPatternConditioned` and the `AnnualSSM`. This module keeps only the
annual path — no import of `scales_ssm_cross_corr_osc_trans`, no ACF term, no
`ctrl_lin` ridge — and changes the two things that made that path behave unlike
a state space model:

1. **z is state again.** It is rolled forward *once* across the whole projection
   and each DiT block reads a slice of that single trajectory.
   `ssm_dit.sample_blocks` re-derived z from the trailing `context_len` window at
   every block, so no latent state survived a block boundary and nothing could
   carry information further back than the context window. Here the transition
   is iterated over the full horizon, so the forced response accumulates
   `B(u_t)` along the entire pathway.

2. **The transition has no oscillator.** Autocorrelation, including the ENSO
   band, is the DiT's job now.

Division of labour
------------------
    z               causal forced-response state: a bank of learned leaky
                    integrators of GSAT, carried across every block
    memory kernels  short-range (<= 20 yr) memory, window-local by design
    month embedding the seasonal cycle
    DiT             everything local, *including* temporal autocorrelation and
                    the ENSO band, which used to be the oscillator's job

Why the oscillator is gone
--------------------------
The damped 2-D rotation existed to put oscillatory structure in z's ACF, and it
only ever earned its amplitude from an ACF loss that the annual model does not
have. The replacement is a per-dimension contraction, `z <- d * z + B(u)` with
`d = sigmoid(.) in (0, 1)`: every eigenvalue is real and inside the unit circle,
so a 140-step rollout is stable by construction and cannot ring. A general dense
`A` is deliberately *not* offered — its eigenvalues are complex in general,
which would smuggle the oscillator back in through the back door.

At initialisation the decays are spread over e-folding times of 1..50 years, so
z starts life as a multi-timescale causal filter bank on the forcing. That is
the same idea as the memory kernels, but stateful and learned, which is what
lets it outlive a block.

Why the conditioning z is the mean, not a sample
------------------------------------------------
With state-independent process noise, a *sampled* rollout approaches its
stationary distribution after a few e-folding times, so blocks deep in the
horizon would be conditioned on a z whose informative content is swamped by
accumulated noise — and the DiT's rational response to that is to learn to
ignore z. Because the transition is linear-Gaussian, mean propagation
`mu <- d * mu + B(u)` is the *exact* conditional mean, not an approximation, so
conditioning on it costs nothing and keeps z a clean forced-response signal.
Internal variability is generated by the diffusion process instead. (A
non-zero `trans_hidden` breaks the exactness — see `roll_forward`.)

Why the forcing memory stays window-local
-----------------------------------------
`mem_u` could be computed over the entire known GSAT path at no leakage cost,
since forcing is known ahead of time. It deliberately is not: a conditioner that
sees the global shape of the trajectory keys on that shape and fails to transfer
to pathways outside the training set, which is the failure this architecture
exists to avoid. Long-range forcing information reaches the DiT only through z,
which is causal by construction.

Known limitation (deferred)
---------------------------
Training is teacher-forced in the *field*: every block's local context is
ground truth, while at sampling time every block after the first sees its own
output. Fixing the z mismatch does not fix that one. If long projections still
drift, compare per-block sample statistics at block 0 against the last block
before blaming z.

Conventions
-----------
The field is `x = cat([tas, pr], dim=-1)`, `2 * y_dim` channels, in normalised
units. One `transition` call is one year (dt = 1 is implicit; the only thing
tying the latent clock to physical time is `to_annual`), so `context_len` and
`block_len` must both be whole years for block boundaries to land on annual
boundaries.
"""

import math

import torch
import torch.nn as nn
import torch.nn.functional as F

from proto_scales.ssm_dit_model.annual_ssm import (
    MONTHS_PER_YEAR,
    broadcast_to_monthly,
    diag_gaussian_kl_per_dim,
    to_annual,
)
from proto_scales.ssm_dit_model.conditioning import ConditioningBuilder
from proto_scales.ssm_dit_model.dit import DiT1D


def cosine_beta_schedule(n_steps, s=0.008):
    """Nichol & Dhariwal cosine schedule."""
    t = torch.linspace(0, n_steps, n_steps + 1, dtype=torch.float64) / n_steps
    f = torch.cos((t + s) / (1.0 + s) * math.pi / 2.0) ** 2
    alpha_bar = f / f[0]
    betas = 1.0 - alpha_bar[1:] / alpha_bar[:-1]
    return betas.clamp(1e-8, 0.999).float()


# ─────────────────────────────────────────────────────────────────────────────
# Latent process
# ─────────────────────────────────────────────────────────────────────────────
class ForcedAnnualSSM(nn.Module):
    """
    Annual linear-Gaussian state space model, non-oscillatory.

        q(z_t | y_<=t, u_<=t) = N(mu_q, diag)          GRU inference network
        p(z_t | z_t-1,  u_t)  = N(d*z_t-1 + B u_t, Q)  contraction + forcing
        p(y_t | z_t,    u_t)  = N(emit([z_t, u_t]), R)

    One step is one year. `y` and `u` are annual means of monthly-standardised
    fields, matching the convention in `annual_ssm`.

    The emission exists for the ELBO and the rollout loss only; the DiT replaces
    it for generation. The linear `u -> y` path through `emit` *is* pattern
    scaling, learned as part of the ELBO, which is why there is no separate
    frozen ridge term.

    Parameters
    ----------
    decay_efold_range : e-folding times in YEARS spanned at initialisation.
                        The default (1, 50) spans interannual to multi-decadal.
    trans_hidden      : optional MLP correction on the transition mean. Off by
                        default; it buys nonlinearity in u (hysteresis) at the
                        cost of making mean propagation approximate rather than
                        exact.
    """

    def __init__(
        self,
        obs_dim,
        u_dim,
        z_dim=16,
        rnn_hidden=64,
        emit_hidden=0,
        trans_hidden=0,
        decay_efold_range=(1.0, 50.0),
    ):
        super().__init__()
        lo, hi = decay_efold_range
        if not (0 < lo <= hi):
            raise ValueError("decay_efold_range must satisfy 0 < low <= high (years)")

        self.obs_dim = obs_dim
        self.u_dim = u_dim
        self.z_dim = z_dim

        # Inference network: q(z_t | y_<=t, u_<=t)
        self.gru = nn.GRU(obs_dim + u_dim, rnn_hidden, batch_first=True)
        self.q_head = nn.Linear(rnn_hidden, 2 * z_dim)

        # Per-dimension contraction, parameterised through a sigmoid so the
        # decay can never leave (0, 1) and the rollout can never diverge.
        tau = torch.logspace(math.log10(lo), math.log10(hi), z_dim)
        d0 = torch.exp(-1.0 / tau).clamp(1e-4, 1 - 1e-4)
        self.logit_decay = nn.Parameter(torch.log(d0 / (1.0 - d0)))
        self.B = nn.Linear(u_dim, z_dim, bias=False)
        self.trans_mlp = (
            nn.Sequential(nn.Linear(z_dim + u_dim, trans_hidden), nn.SiLU(),
                          nn.Linear(trans_hidden, z_dim))
            if trans_hidden else None
        )
        self.log_process_var = nn.Parameter(torch.zeros(z_dim))

        # Emission mean only: an input-dependent variance is a standard way for
        # a model to game a Gaussian NLL.
        emit_in = z_dim + u_dim
        self.emit = (
            nn.Linear(emit_in, obs_dim) if not emit_hidden
            else nn.Sequential(nn.Linear(emit_in, emit_hidden), nn.SiLU(),
                               nn.Linear(emit_hidden, obs_dim))
        )
        self.log_obs_var = nn.Parameter(torch.zeros(obs_dim))

    # -----------------------
    # pieces
    # -----------------------
    def decay(self):
        return torch.sigmoid(self.logit_decay)

    def efolding_years(self):
        """Per-dimension e-folding times in years — the thing to inspect."""
        with torch.no_grad():
            d = self.decay().clamp(1e-6, 1 - 1e-9)
            return (-1.0 / torch.log(d)).cpu()

    def sample(self, mu, logvar):
        return mu + torch.randn_like(mu) * torch.exp(0.5 * logvar)

    def transition_mean(self, z_prev, u_t):
        mu = self.decay() * z_prev + self.B(u_t)
        if self.trans_mlp is not None:
            mu = mu + self.trans_mlp(torch.cat([z_prev, u_t], dim=-1))
        return mu

    def transition(self, z_prev, u_t):
        """Returns (mu_p, logvar_p). Every eigenvalue is real and in (0, 1)."""
        mu_p = self.transition_mean(z_prev, u_t)
        logvar_p = torch.clamp(self.log_process_var, -12.0, 6.0)
        return mu_p, logvar_p.unsqueeze(0).expand(z_prev.shape[0], -1)

    def emit_mean(self, z_t, u_t):
        return self.emit(torch.cat([z_t, u_t], dim=-1))

    # -----------------------
    # latent trajectories
    # -----------------------
    def posterior(self, y, u):
        """Posterior mean over an observed window. Returns ([B,Y,z], [B,z])."""
        h, _ = self.gru(torch.cat([y, u], dim=-1))
        mu_q, _ = torch.chunk(self.q_head(h), 2, dim=-1)
        return mu_q, mu_q[:, -1]

    def roll_forward(self, z0, u_fut, stochastic=False):
        """
        Iterate the transition over `u_fut`. Returns [B, Y_fut, z].

        Keeps the autograd graph: this is used inside the training loss, and a
        `@torch.no_grad()` rollout there would silently contribute exactly zero
        gradient (the trap documented in
        `scales_ssm_cross_corr_osc_trans.rollout_samples`).

        `stochastic=False` propagates the mean, which for this transition is the
        exact conditional mean unless `trans_mlp` is enabled. That is what the
        DiT is conditioned on; see the module docstring.
        """
        z = z0
        out = []
        for k in range(u_fut.shape[1]):
            if stochastic:
                mu_p, logvar_p = self.transition(z, u_fut[:, k])
                z = self.sample(mu_p, logvar_p)
            else:
                z = self.transition_mean(z, u_fut[:, k])
            out.append(z)
        return torch.stack(out, dim=1)

    # -----------------------
    # objectives
    # -----------------------
    def forward_elbo(self, y, u, kl_free_bits=0.05):
        """
        Returns (nll, kl), both normalised per element — nll per
        (year x obs channel), kl per (year x latent dim) — so both are O(1)
        regardless of Y, obs_dim or z_dim and the weights mean the same thing
        when the horizon or the indicator set changes.

        This is a one-step-ahead objective: the transition only ever appears as
        the prior for the next year. It is necessary but not sufficient for the
        long rollouts inference performs, which is what `rollout_loss` is for.
        """
        B, T, _ = y.shape
        h, _ = self.gru(torch.cat([y, u], dim=-1))
        mu_q, logvar_q = torch.chunk(self.q_head(h), 2, dim=-1)
        logvar_q = torch.clamp(logvar_q, -12.0, 6.0)

        log_obs_var = torch.clamp(self.log_obs_var, -12.0, 6.0)
        inv_var = torch.exp(-log_obs_var)

        nll = y.new_zeros(B)
        kl = y.new_zeros(B)
        z_prev = None
        for t in range(T):
            z_t = self.sample(mu_q[:, t], logvar_q[:, t])

            resid = y[:, t] - self.emit_mean(z_t, u[:, t])
            nll = nll + 0.5 * (
                resid * resid * inv_var + log_obs_var + math.log(2.0 * math.pi)
            ).sum(dim=-1)

            if t == 0:
                mu_p = torch.zeros_like(mu_q[:, 0])
                logvar_p = torch.zeros_like(logvar_q[:, 0])
            else:
                mu_p, logvar_p = self.transition(z_prev, u[:, t])
            kl_dim = diag_gaussian_kl_per_dim(
                mu_q[:, t], logvar_q[:, t], mu_p, logvar_p)
            kl = kl + torch.clamp(kl_dim, min=kl_free_bits).sum(dim=-1)

            z_prev = z_t

        return nll.mean() / (T * self.obs_dim), kl.mean() / (T * self.z_dim)

    def rollout_loss(self, y_ctx, u_ctx, y_fut, u_fut):
        """
        Multi-step consistency: the operator inference actually uses.

        From the posterior at the end of the context, roll forward on forcing
        alone for the whole future and require the emission to track the annual
        field at *every* lead. One pass therefore supervises leads 1..Y_fut,
        which is the gap a one-step-ahead ELBO leaves open — a transition can
        fit next-year almost perfectly and still drift over a century.

        Deliberately evaluated on the mean propagation rather than on sampled
        trajectories. The equivalent term in the monthly SSM took an MSE against
        an "ensemble mean" that was a single reparameterised draw at
        `rollout_samples=1`, which made it a variance-collapse term and hurt
        both the ACF and the delayed-warming response. With no sampling there is
        nothing to collapse, and this is exactly the trajectory the DiT is
        conditioned on.

        Returns a per-element MSE (O(1), same scale as the ELBO terms).
        """
        _, z_last = self.posterior(y_ctx, u_ctx)
        z_traj = self.roll_forward(z_last, u_fut, stochastic=False)
        y_hat = self.emit(torch.cat([z_traj, u_fut], dim=-1))
        return ((y_hat - y_fut) ** 2).mean()


# ─────────────────────────────────────────────────────────────────────────────
# Latent encoder
# ─────────────────────────────────────────────────────────────────────────────
class ForcedAnnualLatentEncoder(nn.Module):
    """
    Produces the monthly-resolution latent trajectory the DiT conditions on:
    posterior over the observed context, then one continuous roll forward over
    the entire future.

    The future half must come from the prior roll, never the posterior — a
    posterior that saw the future leaks the target and collapses at sampling
    time. The context half uses the posterior because the context is observed at
    inference too.
    """

    def __init__(self, ssm, freeze=False):
        super().__init__()
        self.ssm = ssm
        self.z_dim = ssm.z_dim
        self.frozen = bool(freeze)
        if self.frozen:
            for p in self.ssm.parameters():
                p.requires_grad = False

    def train(self, mode=True):
        super().train(mode)
        if self.frozen:
            self.ssm.eval()
        return self

    def annual_inputs(self, tas_ctx, pr_ctx, u_ctx, u_fut):
        y_ann = to_annual(torch.cat([tas_ctx, pr_ctx], dim=-1))
        return y_ann, to_annual(u_ctx), to_annual(u_fut)

    def forward(self, tas_ctx, pr_ctx, u_ctx, u_fut, stochastic=False):
        """
        Returns z at monthly resolution over [context + future],
        [B, n_ctx + n_fut, z_dim].

        Note `n_fut` here is the *whole* projection, not one DiT block: blocks
        read slices of this trajectory so that latent state crosses block
        boundaries.
        """
        n_ctx, n_fut = tas_ctx.shape[1], u_fut.shape[1]
        ctx = torch.no_grad() if self.frozen else torch.enable_grad()
        with ctx:
            y_ann, u_ctx_ann, u_fut_ann = self.annual_inputs(
                tas_ctx, pr_ctx, u_ctx, u_fut)
            z_ctx_ann, z_last = self.ssm.posterior(y_ann, u_ctx_ann)
            z_fut_ann = self.ssm.roll_forward(z_last, u_fut_ann, stochastic=stochastic)
            z = torch.cat([broadcast_to_monthly(z_ctx_ann, n_ctx),
                           broadcast_to_monthly(z_fut_ann, n_fut)], dim=1)
        return z.detach() if self.frozen else z


# ─────────────────────────────────────────────────────────────────────────────
# Model
# ─────────────────────────────────────────────────────────────────────────────
class AnnualSSMOutpaintingDiT(nn.Module):
    """
    Parameters
    ----------
    ssm         : a constructed `ForcedAnnualSSM`.
    y_dim       : number of regions. The field has 2*y_dim channels.
    u_dim       : forcing dimension (1 for GSAT).
    context_len : observed months the DiT attends over, per block.
    block_len   : months generated per block (the old `horizon`). The DiT window
                  is always `context_len + block_len` tokens regardless of how
                  long the projection is.
    timescales_years : memory-kernel relaxation times. The default drops the
                  100 yr kernel that `ssm_dit` carried: the kernels are
                  window-local and re-zero their EMA on every call, so over a
                  240-month window a 100 yr kernel never leaves its ramp-up
                  transient. Century-scale memory is z's job here.
    """

    def __init__(
        self,
        ssm,
        y_dim,
        u_dim,
        context_len=120,
        block_len=120,
        freeze_ssm=False,
        cond_dim=256,
        hidden=384,
        depth=8,
        heads=6,
        n_diffusion_steps=1000,
        timescales_years=(1.0, 5.0, 20.0),
        learnable_timescales=True,
        field_memory_rank=32,
        parameterization="v",
        stochastic_z=False,
        # auxiliary SSM objectives
        ssm_elbo_weight=1.0,
        ssm_kl_weight=5.0,
        ssm_kl_free_bits=0.2,
        ssm_rollout_weight=1.0,
    ):
        super().__init__()
        if parameterization not in ("v", "eps"):
            raise ValueError("parameterization must be 'v' or 'eps'")
        # Whole years, so that to_annual's year boundaries coincide with block
        # boundaries. Without this a block advances the shared rollout by a full
        # year for a fraction of a year of forcing.
        if int(context_len) % MONTHS_PER_YEAR or int(block_len) % MONTHS_PER_YEAR:
            raise ValueError(
                f"context_len and block_len must be whole years (multiples of "
                f"{MONTHS_PER_YEAR}); got {context_len} and {block_len}")
        if int(context_len) < 2 * MONTHS_PER_YEAR:
            # Fewer than two complete years and every month maps to the zero
            # "year -1" state of the causal annual EMA, so the field memory is
            # identically zero, its parameters get no gradient, and DDP raises
            # on unreduced parameters.
            raise ValueError(
                f"context_len must be >= {2 * MONTHS_PER_YEAR} months (got "
                f"{context_len})")

        self.y_dim = y_dim
        self.u_dim = u_dim
        self.context_len = int(context_len)
        self.block_len = int(block_len)
        self.n_total = self.context_len + self.block_len
        self.in_channels = 2 * y_dim
        self.n_diffusion_steps = int(n_diffusion_steps)
        self.parameterization = parameterization
        self.stochastic_z = bool(stochastic_z)

        self.ssm_elbo_weight = float(ssm_elbo_weight)
        self.ssm_kl_weight = float(ssm_kl_weight)
        self.ssm_kl_free_bits = float(ssm_kl_free_bits)
        self.ssm_rollout_weight = float(ssm_rollout_weight)
        self.use_ssm_aux = (not freeze_ssm) and (
            self.ssm_elbo_weight > 0 or self.ssm_rollout_weight > 0)

        self.ssm_encoder = ForcedAnnualLatentEncoder(ssm, freeze=freeze_ssm)
        self.cond_builder = ConditioningBuilder(
            y_dim=y_dim,
            u_dim=u_dim,
            z_dim=self.ssm_encoder.z_dim,
            cond_dim=cond_dim,
            timescales_years=timescales_years,
            learnable_timescales=learnable_timescales,
            field_memory_rank=field_memory_rank,
        )
        self.dit = DiT1D(
            in_channels=self.in_channels,
            cond_dim=cond_dim,
            max_len=self.n_total,
            hidden=hidden,
            depth=depth,
            heads=heads,
        )

        betas = cosine_beta_schedule(self.n_diffusion_steps)
        alphas = 1.0 - betas
        alpha_bar = torch.cumprod(alphas, dim=0)
        self.register_buffer("betas", betas)
        self.register_buffer("alphas", alphas)
        self.register_buffer("alpha_bar", alpha_bar)
        self.register_buffer("sqrt_ab", alpha_bar.sqrt())
        self.register_buffer("sqrt_1mab", (1.0 - alpha_bar).sqrt())

    # ------------------------------------------------------------------
    # conditioning
    # ------------------------------------------------------------------
    def latents(self, tas_ctx, pr_ctx, u_ctx, u_fut):
        """z over the whole super-window, [B, n_ctx + n_fut, z_dim]."""
        return self.ssm_encoder(tas_ctx, pr_ctx, u_ctx, u_fut,
                                stochastic=self.stochastic_z)

    def window_conditioning(self, z_win, u_win, field_ctx, n_block, start_month):
        """
        Conditioning for one DiT window: `context_len` observed months followed
        by `n_block` generated months.

        `z_win` is a slice of the single long trajectory, so for any block past
        the first *both* halves of the window carry rolled-forward state — which
        is exactly what the sampler sees.
        """
        return self.cond_builder(
            z=z_win,
            u_full=u_win,
            field_ctx=field_ctx,
            n_ctx=self.context_len,
            n_total=self.context_len + n_block,
            start_month=start_month,
        )

    def _mask(self, B, n_ctx, n_total, device):
        """1 on observed context positions, 0 on generated positions."""
        mask = torch.zeros(B, n_total, 1, device=device)
        mask[:, :n_ctx] = 1.0
        return mask

    def _to_x0_eps(self, pred, x_t, t):
        """
        Convert the network output to (x0_hat, eps_hat). `t` is a scalar index.

        With v-parameterisation, v = a*eps - s*x0 and a^2 + s^2 = 1, so the
        inverse is the rotation x0 = a*x_t - s*v, eps = s*x_t + a*v, which stays
        well conditioned at every noise level. The eps route divides by a -> 0 at
        high noise and amplifies any error in eps_hat without bound.
        """
        a = self.sqrt_ab[t]
        s = self.sqrt_1mab[t]
        if self.parameterization == "v":
            x0_hat = a * x_t - s * pred
            eps_hat = s * x_t + a * pred
        else:
            eps_hat = pred
            x0_hat = (x_t - s * eps_hat) / a.clamp(min=1e-8)
        x0_hat = x0_hat.clamp(-10.0, 10.0)
        # Re-derive eps from the clamped x0 so the pair stays self-consistent;
        # an inconsistent (x0, eps) pair injects a bias into the DDIM step.
        eps_hat = (x_t - a * x0_hat) / s.clamp(min=1e-8)
        return x0_hat, eps_hat

    def block_bounds(self, block_idx, n_fut):
        """
        Absolute month bounds of DiT block `block_idx` inside a super-window
        whose future part is `n_fut` months long.

        Returns (win_start, block_start, n_block); the DiT window is
        [win_start, block_start + n_block) and always `context_len` months of
        history followed by the block.
        """
        block_start = self.context_len + int(block_idx) * self.block_len
        n_block = min(self.block_len, self.context_len + n_fut - block_start)
        if n_block <= 0:
            raise IndexError(
                f"block_idx {block_idx} is past the end of a {n_fut}-month future")
        return block_start - self.context_len, block_start, n_block

    def n_blocks(self, n_fut):
        return max(1, math.ceil(n_fut / self.block_len))

    # ------------------------------------------------------------------
    # training
    # ------------------------------------------------------------------
    def forward(self, *args, **kwargs):
        """
        Alias for `loss` so the module can be called through a DDP wrapper.

        DDP synchronises gradients via hooks armed by the forward pass on the
        *wrapped* module. Calling an inner method directly bypasses the reducer
        and each rank then trains on its own shard without averaging.
        """
        return self.loss(*args, **kwargs)

    def diffusion_loss(self, z_win, u_win, field_win, n_block, start_month,
                       t_diff=None):
        """
        Diffusion loss on the generated positions of one window.

        The context positions are held at their clean values throughout, so the
        denoiser always sees an intact history — that is the outpainting
        condition, and it is what the model sees at sampling time.
        """
        B = field_win.shape[0]
        device = field_win.device
        n_ctx = self.context_len
        n_total = n_ctx + n_block

        field_ctx = field_win[:, :n_ctx]
        cond = self.window_conditioning(z_win, u_win, field_ctx, n_block, start_month)

        x0 = field_win
        mask = self._mask(B, n_ctx, n_total, device)

        if t_diff is None:
            t_diff = torch.randint(0, self.n_diffusion_steps, (B,), device=device)
        eps = torch.randn_like(x0)
        a = self.sqrt_ab[t_diff].view(B, 1, 1)
        s = self.sqrt_1mab[t_diff].view(B, 1, 1)
        x_noisy = a * x0 + s * eps
        x_in = mask * x0 + (1.0 - mask) * x_noisy

        pred = self.dit(x_in, t_diff, cond, mask)
        target = (a * eps - s * x0) if self.parameterization == "v" else eps

        gen = 1.0 - mask
        denom = gen.sum() * x0.shape[-1]
        return ((pred - target) ** 2 * gen).sum() / denom.clamp(min=1.0)

    def ssm_aux_loss(self, tas_ctx, pr_ctx, u_ctx, tas_fut, pr_fut, u_fut):
        """
        The SSM's own objectives, evaluated inside the DiT forward so they join
        the same DDP reduction.

        ELBO     keeps z a genuine latent state of the data rather than whatever
                 the diffusion loss finds convenient, one year ahead;
        rollout  is the only term that scores the many-step operator the sampler
                 actually iterates. Without it, century rollouts are an
                 unsupervised extrapolation from a next-year fit.
        """
        enc = self.ssm_encoder
        y_ann = to_annual(torch.cat([torch.cat([tas_ctx, tas_fut], dim=1),
                                     torch.cat([pr_ctx, pr_fut], dim=1)], dim=-1))
        u_ann = to_annual(torch.cat([u_ctx, u_fut], dim=1))

        parts = {}
        total = torch.zeros((), device=y_ann.device)

        if self.ssm_elbo_weight > 0:
            nll, kl = enc.ssm.forward_elbo(
                y_ann, u_ann, kl_free_bits=self.ssm_kl_free_bits)
            total = total + self.ssm_elbo_weight * (nll + self.ssm_kl_weight * kl)
            parts["ssm_nll"] = nll.detach()
            parts["ssm_kl"] = kl.detach()

        if self.ssm_rollout_weight > 0:
            y_ctx_ann, u_ctx_ann, u_fut_ann = enc.annual_inputs(
                tas_ctx, pr_ctx, u_ctx, u_fut)
            n_ctx_yr = y_ctx_ann.shape[1]
            roll = enc.ssm.rollout_loss(
                y_ctx_ann, u_ctx_ann, y_ann[:, n_ctx_yr:], u_fut_ann)
            total = total + self.ssm_rollout_weight * roll
            parts["ssm_rollout"] = roll.detach()

        return total, parts

    def loss(self, tas_ctx, pr_ctx, u_ctx, tas_fut, pr_fut, u_fut,
             block_idx=(0,), start_month=0, t_diff=None, return_parts=False):
        """
        Loss over a super-window: `context_len` observed months plus a long
        future, with the diffusion term evaluated on the DiT blocks listed in
        `block_idx`.

        z is rolled once over the whole future and each block reads its slice, so
        blocks late in `block_idx` are trained on latents that carry the full
        accumulated forcing history — the statistics the sampler produces. That
        is the point of training on long horizons; a single 10-year rollout only
        ever shows the model the first block's z.

        Blocks share the rollout, so adding offsets costs a DiT pass each and no
        extra SSM work. They also share the batch, so the effective batch is
        `batch_size * len(block_idx)`.
        """
        n_fut = u_fut.shape[1]
        z_all = self.latents(tas_ctx, pr_ctx, u_ctx, u_fut)
        field_all = torch.cat([torch.cat([tas_ctx, tas_fut], dim=1),
                               torch.cat([pr_ctx, pr_fut], dim=1)], dim=-1)
        u_all = torch.cat([u_ctx, u_fut], dim=1)

        if isinstance(block_idx, torch.Tensor):
            block_idx = block_idx.tolist()
        elif isinstance(block_idx, int):
            block_idx = [block_idx]

        diff_terms = []
        per_block = {}
        for bi in block_idx:
            w0, bs, nb = self.block_bounds(bi, n_fut)
            win = slice(w0, bs + nb)
            d = self.diffusion_loss(
                z_win=z_all[:, win],
                u_win=u_all[:, win],
                field_win=field_all[:, win],
                n_block=nb,
                start_month=(int(start_month) + w0) % MONTHS_PER_YEAR,
                t_diff=t_diff,
            )
            diff_terms.append(d)
            # Reported per block so one call can show the drift with lead time;
            # recomputing the loss per block would redo the ELBO and the rollout.
            per_block[f"diff_blk{int(bi)}"] = d.detach()
        diff_loss = torch.stack(diff_terms).mean()

        parts = {"diffusion": diff_loss.detach()}
        if len(per_block) > 1:
            parts.update(per_block)
        total = diff_loss
        if self.use_ssm_aux:
            aux, aux_parts = self.ssm_aux_loss(
                tas_ctx, pr_ctx, u_ctx, tas_fut, pr_fut, u_fut)
            total = total + aux
            parts.update(aux_parts)
            parts["ssm_aux_weighted"] = aux.detach()

        return (total, parts) if return_parts else total

    # ------------------------------------------------------------------
    # sampling
    # ------------------------------------------------------------------
    @torch.no_grad()
    def _sample_window(self, cond, field_ctx, n_block, n_steps=None, generator=None):
        """Ancestral/DDIM sampling of one block. Returns [B, n_block, 2*y_dim]."""
        B = field_ctx.shape[0]
        device = field_ctx.device
        n_ctx = field_ctx.shape[1]
        n_total = n_ctx + n_block

        mask = self._mask(B, n_ctx, n_total, device)
        obs = F.pad(field_ctx, (0, 0, 0, n_block))

        x = torch.randn(B, n_total, self.in_channels, device=device, generator=generator)
        x = mask * obs + (1.0 - mask) * x

        total = self.n_diffusion_steps
        n_steps = total if n_steps is None else int(n_steps)
        step_idx = torch.linspace(total - 1, 0, n_steps, device=device).long()

        for i, t in enumerate(step_idx):
            pred = self.dit(x, t.repeat(B), cond, mask)
            ab_t = self.alpha_bar[t]
            x0_hat, eps_hat = self._to_x0_eps(pred, x, t)

            if i < len(step_idx) - 1:
                ab_prev = self.alpha_bar[step_idx[i + 1]]
                sigma = ((1 - ab_prev) / (1 - ab_t)).sqrt() * (1 - ab_t / ab_prev).sqrt()
                dir_xt = (1 - ab_prev - sigma**2).clamp(min=0).sqrt() * eps_hat
                noise = torch.randn(x.shape, device=device, generator=generator)
                x = ab_prev.sqrt() * x0_hat + dir_xt + sigma * noise
            else:
                x = x0_hat

            # re-impose the observed context at every step
            x = mask * obs + (1.0 - mask) * x

        return x[:, n_ctx:]

    @torch.no_grad()
    def sample_blocks(self, tas_ctx, pr_ctx, u_ctx, u_fut, start_month=0,
                      n_steps=None, generator=None):
        """
        Long-horizon generation. `u_fut` may be arbitrarily long.

        z is rolled forward **once** over the whole projection before any
        sampling happens, and each block reads its slice. That is the difference
        from `ssm_dit.sample_blocks`, which re-derived z from the trailing
        context window per block and so could not carry information further back
        than `context_len`. Here the latent is a genuine state: the forced
        response at year 100 has integrated the whole pathway.

        The field context still slides — each block is conditioned on the
        previous `context_len` months, generated rather than observed after the
        first block — so cost stays linear in the horizon and the DiT is never
        asked to attend over a window it was not trained on.

        Returns (tas, pr), each [B, len(u_fut), y_dim].
        """
        H_total = u_fut.shape[1]
        z_all = self.latents(tas_ctx, pr_ctx, u_ctx, u_fut)
        u_all = torch.cat([u_ctx, u_fut], dim=1)
        field_hist = torch.cat([tas_ctx, pr_ctx], dim=-1)

        out = []
        done = 0
        while done < H_total:
            w0, bs, nb = self.block_bounds(done // self.block_len, H_total)
            win = slice(w0, bs + nb)
            field_ctx = field_hist[:, w0:bs]
            cond = self.window_conditioning(
                z_win=z_all[:, win],
                u_win=u_all[:, win],
                field_ctx=field_ctx,
                n_block=nb,
                start_month=(int(start_month) + w0) % MONTHS_PER_YEAR,
            )
            blk = self._sample_window(cond, field_ctx, nb, n_steps, generator)
            field_hist = torch.cat([field_hist, blk], dim=1)
            out.append(blk)
            done += nb

        fut = torch.cat(out, dim=1)
        return fut[..., : self.y_dim], fut[..., self.y_dim:]


def build_model(y_dim, u_dim, device="cpu", ssm_weights=None, **kwargs):
    """
    Convenience constructor. `ssm_weights` optionally warm-starts the latent
    process from a standalone `ForcedAnnualSSM` run; unexpected keys are ignored.
    """
    ssm = ForcedAnnualSSM(
        obs_dim=2 * y_dim,
        u_dim=u_dim,
        z_dim=kwargs.pop("z_dim", 16),
        rnn_hidden=kwargs.pop("rnn_hidden", 64),
        emit_hidden=kwargs.pop("emit_hidden", 0),
        trans_hidden=kwargs.pop("trans_hidden", 0),
        decay_efold_range=kwargs.pop("decay_efold_range", (1.0, 50.0)),
    )
    if ssm_weights is not None:
        ckpt = torch.load(ssm_weights, map_location="cpu")
        missing, unexpected = ssm.load_state_dict(ckpt, strict=False)
        if missing:
            print(f"[build_model] SSM missing keys: {missing}")
        if unexpected:
            print(f"[build_model] SSM unexpected keys ignored: {len(unexpected)}")

    model = AnnualSSMOutpaintingDiT(ssm=ssm, y_dim=y_dim, u_dim=u_dim, **kwargs)
    return model.to(device)
